plex-configuration:
  image: busybox
  container_name: plex-data
  command: "true"
  volumes:
      - /config

plex:
    image: timhaak/plex
    net: host
    ports:
    - "32400:32400"
    volumes_from:
    - plex-configuration:rw
labels:
    io.rancher.sidekicks: plex-configuration 
