plex-config:
    image: busybox:latest
    net: none
    command: "true"
    volumes:
        - /config

plex-data:
    image: busybox:latest
    net: none
    command: "true"
    volumes:
        - /data

plex:
    image: timhaak/plex:latest
    restart: always
    ports:
        - 32400
    volumes_from:
        - plex-config
        - plex-data
    environment:
        PLEX_USERNAME: ${PLEX_USERNAME}
        PLEX_PASSWORD: ${PLEX_PASSWORD}

